# Config file for an example Majora's Mask: Recompiled mod.

# Fields that end up in the mod's manifest.
[manifest]

# Unique ID of this mod. Pick something long enough that it'll never be the same as any other mod.
# The name displayed in the mod management menu is separate from this so this doesn't need to be human readable.
id = "jackie_redux_mod"

# Version of this mod.
version = "2.0.0"

# The name that will show up for this mod in the mod menu. This should be human readable.
display_name = "Jackie Quilt Redux Mod"

# The description that will show up when this mod is displayed in the mod menu. This should be human readable.
description =  """
A mod that replaces Link with Jackie from Eternal Return.

This mod contains an alternative hair style and Cadet costume that use real-time physics.

NOTE: This mod does not use Neirn's Player Model Manager, so there may be compatibility issues with it if you have it enabled.

WARNING: Performance of Cadet costume may vary based on the quality of your hardware.
"""

# A short description that will show up in this mod's entry in the mod list. This should be human readable and kept short
# to prevent it from being cut off due to the limited space.
short_description = "Replaces Link with Jackie"

# Authors of this mod.
authors = [ "Bigmetalhead12" ]

# ID of the target recomp game.
game_id = "mm"

# Minimum version of the target recomp (e.g. Zelda 64: Recompiled) that this mod can run on.
minimum_recomp_version = "1.2.0"

# Dependency mods. Each entry is the mod's ID and then an optional minimum version of the dependency mod.
dependencies = [
	"magemods_audio_api",
	"MM_EZ_Text_Replacer_API",
	"ProxyMM_CustomActor"
]

# Native libraries (e.g. DLLs) and the functions they export.
native_libraries = [
# Example native library:
#    { name = "my_native_library", funcs = ["my_native_library_function"] }
]

# Inputs to the mod tool.
[inputs]

# Input elf file to generate a mod from.
elf_path = "build/mod.elf"

# Output mod filename.
mod_filename = "jackie_redux_mod"

# Reference symbol files.
func_reference_syms_file = "Zelda64RecompSyms/mm.us.rev1.syms.toml"
data_reference_syms_files = [ "Zelda64RecompSyms/mm.us.rev1.datasyms.toml", "Zelda64RecompSyms/mm.us.rev1.datasyms_static.toml" ]

# Additional files to include in the mod.
additional_files = [ "thumb.png", 
						"hdtextures/eyes_open.dds",
						"hdtextures/eyes_half.dds",
						"hdtextures/eyes_closed.dds",
						"hdtextures/eyes_roll_right.dds",
						"hdtextures/eyes_roll_left.dds",
						"hdtextures/eyes_roll_down.dds",
						"hdtextures/eyes_shocked.dds",
						"hdtextures/mouth_default.dds",
						"hdtextures/mouth_half.dds",
						"hdtextures/mouth_open.dds",
						"hdtextures/mouth_smile.dds",
						"hdtextures/hair3.dds",
						"hdtextures/hair.dds",
						"hdtextures/hair2.dds",
						"hdtextures/face_scar.dds",
						"hdtextures/nose.dds",
						"hdtextures/skin_with_shading.dds",
						"hdtextures/skin.dds",
						"hdtextures/chocker_neck.dds",
						"hdtextures/torso_frontleft.dds",
						"hdtextures/torso_frontright.dds",
						"hdtextures/torso_frontbotleft.dds",
						"hdtextures/torso_frontbotright.dds",
						"hdtextures/torso_right.dds",
						"hdtextures/torso_left.dds",
						"hdtextures/back_topleft.dds",
						"hdtextures/back_topright.dds",
						"hdtextures/back_botleft.dds",
						"hdtextures/back_botright.dds",
						"hdtextures/ring_decal.dds",
						"hdtextures/pants_frontleft.dds",
						"hdtextures/pants_frontright.dds",
						"hdtextures/pants_backleft.dds",
						"hdtextures/pants_backright.dds",
						"hdtextures/thigh_left.dds",
						"hdtextures/thigh_left_scar.dds",
						"hdtextures/thigh_right.dds",
						"hdtextures/lowerleg_left.dds",
						"hdtextures/lowerleg_left_back.dds",
						"hdtextures/shoe_top_hole.dds",
						"hdtextures/shoe_top_front.dds",
						"hdtextures/shoe_top_back.dds",
						"hdtextures/shoe_top_ark.dds",
						"hdtextures/shoe_bot.dds",
						"hdtextures/shoe_sole_left.dds",
						"hdtextures/apron_white.dds",
						"hdtextures/apron_front.dds",
						"hdtextures/apron.dds",
						"hdtextures/apron_strap_top.dds",
						"hdtextures/apron_strap.dds",
						"hdtextures/strap_hook.dds",
						"hdtextures/belt.dds",
						"hdtextures/pouch_front.dds",
						"hdtextures/pouch_back.dds",
						"hdtextures/upperarm_left_front.dds",
						"hdtextures/upperarm_left_back.dds",
						"hdtextures/lowerarm_left_front.dds",
						"hdtextures/lowerarm_left_back.dds",
						"hdtextures/upperarm_right_front.dds",
						"hdtextures/upperarm_right_back.dds",
						"hdtextures/lowerarm_right_front.dds",
						"hdtextures/lowerarm_right_back.dds",
						"hdtextures/glove_wrist_top.dds",
						"hdtextures/glove_wrist_bot.dds",
						"hdtextures/glove_fingers_top.dds",
						"hdtextures/glove_fingers_bot.dds",
						"hdtextures/glove_thumb_top.dds",
						"hdtextures/glove_thumb_bot.dds",
						"hdtextures/glove_fist_top.dds",
						"hdtextures/glove_fist_bot.dds",
						"hdtextures/glove_fist_front.dds",
						"hdtextures/glove_fist_back.dds",
						"hdtextures/glove_fist_front_fp.dds",
						"hdtextures/glove_fist_fingers_fp.dds",
						"hdtextures/ear.dds",
						"hdtextures/elegy_eyes.dds",
						"hdtextures/collar.dds",
						"hdtextures/dress_shirt_front_right.dds",
						"hdtextures/dress_shirt_front_left.dds",
						"hdtextures/jacket_collar.dds",
						"hdtextures/jacket_collar_back.dds",
						"hdtextures/jacket_front_right.dds",
						"hdtextures/jacket_front_left.dds",
						"hdtextures/jacket_back.dds",
						"hdtextures/jacket_shoulder.dds",
						"hdtextures/jacket_arm_front.dds",
						"hdtextures/jacket_arm_back.dds",
						"hdtextures/skirt_trim.dds",
						"hdtextures/dress_trim.dds",
						"hdtextures/skin_arm_back.dds",
						"hdtextures/skin_fingers_top.dds",
						"hdtextures/skin_fingers_bot.dds",
						"hdtextures/skin_thumb.dds",
						"hdtextures/skin_fist_top.dds",
						"hdtextures/skin_fist_front.dds",
						"hdtextures/skin_fist_bot.dds",
						"hdtextures/skin_fist_back.dds",
						"hdtextures/corset.dds",
						"hdtextures/skirt_front.dds",
						"hdtextures/skirt.dds",
						"hdtextures/lowerleg_front.dds",
						"hdtextures/shoe_strings_top.dds",
						"hdtextures/shoe_strings_bot.dds",
						"hdtextures/shoe_bot_elegy.dds",
						"hdtextures/hat_cap_HD.dds",
						"hdtextures/hat_column1_HD.dds",
						"hdtextures/hat_column2_HD.dds",
						"hdtextures/hat_side_strap_HD.dds",
						"hdtextures/hat_side_strap_small_HD.dds",
						"hdtextures/hat_side_strap_gold_HD.dds",
						"hdtextures/hat_logo_HD.dds",
						"hdtextures/hat_strap1_HD.dds",
						"hdtextures/hat_strap_gold_holder_HD.dds",
						"hdtextures/hat_column_holder_HD.dds",
						"hdtextures/back_shoulder_gold_button_HD.dds",
						"hdtextures/hat_strap_hook_HD.dds",
						"hdtextures/hat_side_strap_gold2_HD.dds",
						"hdtextures/wrist_cuff_chain_HD.dds",
						"hdtextures/hat_cap1_HD.dds",
						"hdtextures/hat_cap2_HD.dds",
						"hdtextures/hat_cap3_HD.dds",
						"hdtextures/necklace_HD.dds",
						"hdtextures/necklace_gold_HD.dds",
						"hdtextures/torso_left_HD.dds",
						"hdtextures/torso_right_HD.dds",
						"hdtextures/coat_front_HD.dds",
						"hdtextures/coat_back_HD.dds",
						"hdtextures/collar_botleft_HD.dds",
						"hdtextures/collar_botright_HD.dds",
						"hdtextures/collar_topleft_HD.dds",
						"hdtextures/collar_topright_HD.dds",
						"hdtextures/collar_badge_HD.dds",
						"hdtextures/back_shoulder_HD.dds",
						"hdtextures/back_shoulder_strap_HD.dds",
						"hdtextures/back_shoulder_strap_end1_HD.dds",
						"hdtextures/back_shoulder_strap_end2_HD.dds",
						"hdtextures/back_shoulder_silver_HD.dds",
						"hdtextures/back_shoulder_gold_emblem_HD.dds",
						"hdtextures/lowerarm_back_HD.dds",
						"hdtextures/lowerarm_front_HD.dds",
						"hdtextures/glove_fingers_top_HD.dds",
						"hdtextures/glove_thumb_HD.dds",
						"hdtextures/glove_thumb2_HD.dds",
						"hdtextures/wrist_cuff_open_HD.dds",
						"hdtextures/wrist_cuff_closed_HD.dds",
						"hdtextures/wrist_strap_HD.dds",
						"hdtextures/armband1_HD.dds",
						"hdtextures/armband2_HD.dds",
						"hdtextures/coat_cuff_outside1_left_HD.dds",
						"hdtextures/coat_cuff_outside1_right_HD.dds",
						"hdtextures/coat_cuff_outside2_HD.dds",
						"hdtextures/coat_cuff_inside1_left_HD.dds",
						"hdtextures/coat_cuff_inside1_right_HD.dds",
						"hdtextures/coat_cuff_inside2_left_HD.dds",
						"hdtextures/coat_cuff_inside2_right_HD.dds",
						"hdtextures/coat_forearm_front_HD.dds",
						"hdtextures/coat_forearm_back_HD.dds",
						"hdtextures/coat_shoulder_HD.dds",
						"hdtextures/coat_cuff_strap1_HD.dds",
						"hdtextures/coat_cuff_strap2_HD.dds",
						"hdtextures/coat_cuff_strap3_HD.dds",
						"hdtextures/coat_cuff_strap_holder_HD.dds",
						"hdtextures/wrist_cuff_gold_button_HD.dds",
						"hdtextures/belt_holder_HD.dds",
						"hdtextures/belt_buckle_HD.dds",
						"hdtextures/belt_buckle_pin_HD.dds",
						"hdtextures/belt_HD.dds",
						"hdtextures/belt_logo_HD.dds",
						"hdtextures/skirt_front_HD.dds",
						"hdtextures/skirt_front_left_HD.dds",
						"hdtextures/skirt_front_right_HD.dds",
						"hdtextures/skirt_front_right2_HD.dds",
						"hdtextures/skirt_rear_HD.dds",
						"hdtextures/tight_thigh_left_HD.dds",
						"hdtextures/tight_thigh_right_HD.dds",
						"hdtextures/tight_lowerleg_front_HD.dds",
						"hdtextures/tight_lowerleg_back_HD.dds",
						"hdtextures/boots_strings_bot_HD.dds",
						"hdtextures/boots_strings_mid_HD.dds",
						"hdtextures/boots_strings_top_HD.dds",
						"hdtextures/boots_bot_HD.dds",
						"hdtextures/boots_back_bot_HD.dds",
						"hdtextures/boots_heel_HD.dds",
						"hdtextures/bootstrap_mid_HD.dds",
						"hdtextures/bootstrap_silver_HD.dds",
						"hdtextures/bootstrap_end_HD.dds",
						"hdtextures/glove_fist_top_HD.dds",
						"hdtextures/glove_fist_front_HD.dds",
						"hdtextures/glove_fist_bot_HD.dds",
						"hdtextures/glove_fist_back_HD.dds",
						"hdtextures/coat_trim_HD.dds",
						"hdtextures/coat_cuff_trim_back1_HD.dds",
						"hdtextures/coat_cuff_trim_back3_HD.dds",
						"hdtextures/coat_cuff_trim_back3_1_HD.dds",
						"hdtextures/coat_cuff_trim_front1_HD.dds",
						"hdtextures/coat_cuff_trim_front2_HD.dds",
						"hdtextures/coat_cuff_trim_front2_1_HD.dds",
						"hdtextures/coat_cuff_button_HD.dds",
						"hdtextures/wrist_gold_HD.dds",
						"hdtextures/wrist_gold_shade_HD.dds",
						"hdtextures/wrist_strap_shade_HD.dds",
						"hdtextures/wrist_cuff_gold_HD.dds",
						"hdtextures/wrist_cuff_HD.dds",
						"hdtextures/wrist_cuff2_HD.dds",
						"hdtextures/glove_finger_HD.dds",
						"hdtextures/glove_white_HD.dds",
						"hdtextures/glove_white2_HD.dds",
						"hdtextures/coat_fold2_HD.dds",
						"hdtextures/belt_strap_holder_HD.dds",
						"hdtextures/belt_strap_gold_end_HD.dds",
						"hdtextures/belt_strap_connector_HD.dds",
						"hdtextures/belt_strap_connector_inside_HD.dds",
						"hdtextures/belt_strap_HD.dds",
						"hdtextures/belt_strap_end2_HD.dds",
						"hdtextures/belt_strap_end1_HD.dds",
						"hdtextures/torso_front_HD.dds",
						"hdtextures/torso_back_HD.dds",
						"hdtextures/overcoat_beltstrap_HD.dds",
						"hdtextures/overcoat_beltstrap_bot_HD.dds",
						"hdtextures/overcoat_front_high_HD.dds",
						"hdtextures/overcoat_front_low_HD.dds",
						"hdtextures/overcoat_back_high_HD.dds",
						"hdtextures/overcoat_back_low_HD.dds",
						"hdtextures/overcoat_pocket_HD.dds",
						"hdtextures/belt_strap_side_end2_HD.dds",
						"hdtextures/rt64.json",
						"hdtextures/rt64-low-mip-cache.bin"]
						
[[manifest.config_options]]
id = "_recomp_texture_pack_enabled"
name = "Enable HD Textures"
description = """
Toggle on to enable HD textures for Jackie.
"""
type = "Enum"
options = [ "Off", "On" ]
default = "Off"

[[manifest.config_options]]
id = "change_hairstyle"
name = "Change Hairstyle"
description = """
Toggle to change the hairstyle (Default or Ponytail)

Note that the ponytail uses real-time physics, and its performance may vary based on your PC's hardware.
"""
type = "Enum"
options = [ "Default", "Ponytail" ]
default = "Default"

[[manifest.config_options]]
id = "change_outfit"
name = "Change Outfit"
description = """
Toggle to change the outfit (Default or Cadet)

Note that the Cadet costume uses real-time physics, and its performance may vary based on your PC's hardware.
"""
type = "Enum"
options = [ "Default", "Cadet" ]
default = "Default"

[[manifest.config_options]]
id = "alternative_text"
name = "Change Text"
description = """
Toggle to change the text (Default or Alternative)
"""
type = "Enum"
options = [ "Default", "Alternative" ]
default = "Default"

